# My preferred dev tools
brew "bat"
brew "direnv"
brew "eza"
brew "fd"
brew "fish"
brew "fzf"
brew "git-delta"
brew "jq"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "zoxide"
brew "cloc"
brew "fnm"

# --- Neovim plugin dependencies ---

# lazy.nvim
brew "luarocks"

# conform.nvim
#brew "stylua"

# --- Not required but good to have installed ---
brew "wget"
brew "ssh-copy-id"

# --- Other dependencies ---
# wget
brew "libidn2"
