[terminal]
[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-l"]

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# https://github.com/alacritty/alacritty/issues/7608#issuecomment-1975006973
[[keyboard.bindings]]
chars = "\u001f"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[window]
decorations = "buttonless"
startup_mode = "Maximized"

[window.padding]
x = 14
y = 10

[general]
live_config_reload = true
import = ["/Users/mpanelo/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_night.toml"]
