############################
# Mau's Tmux Configuration #
############################

# Cheatsheet - https://tmuxcheatsheet.com/

set-option -g default-shell /opt/homebrew/bin/fish

# Stay in tmux when a session is killed
set -g detach-on-destroy off

set -g status-position bottom

# Use 1-based indexing when creating windows
set -g base-index 1

# Renumber windows when a window is closed
set -g renumber-windows on

# Support 256 color
set -g default-terminal "tmux-256color"

# Undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Mouse mode
set -g mouse on

# Sane split commands
unbind '"'
bind | split-window -c '#{pane_current_path}' -h

unbind %
bind - split-window -c '#{pane_current_path}' -v

# Keep the current path when creating a new window
bind c new-window -c '#{pane_current_path}'

# Vim style pane-switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

# Vim style window rotation
bind R swap-window -d -t -1
bind r swap-window -d -t +1

bind C-b switch-client -l

set-window-option -g mode-keys vi

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# Close panes without confirmation
bind x kill-pane

bind g popup -E -w 90% -h 90% -x C -y C -b none -d '#{pane_current_path}' "lazygit"
bind C-p run-shell 'popuptmux'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Configure the catppuccin plugin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_current_text " #W "
set -g @catppuccin_window_text " #W "

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Custom status line
set -g status-left-length 100
set -g status-right-length 100
set -g window-status-separator ''
set -g status-left '#{E:@catppuccin_status_session}'
set -gF status-right '#{E:@catppuccin_status_continuum}#{E:@catppuccin_status_battery}'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-battery'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
