############################
# Mau's Tmux Configuration #
############################

# Cheatsheet - https://tmuxcheatsheet.com/

set-option -g default-shell /opt/homebrew/bin/fish

set -g status-position bottom

set -g base-index 1          # Use 1-based indexing when creating windows
setw -g mode-keys vi         # Vi bindings in copy mode
set -sg escape-time 10       # 10ms delay after Esc
set -g detach-on-destroy off # Stay in tmux when a session is killed
set -g renumber-windows on   # Renumber windows when a window is closed

# Support 256 color
set -g default-terminal "tmux-256color"

# Undercurl support for neovim diagnostics
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Mouse mode
set -g mouse on

# Vim-like split keybindings
unbind '"'
unbind %
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind Escape copy-mode # Mimics entering "normal" mode in nvim

# Keep the current path when creating a new window
bind c new-window -c '#{pane_current_path}'

bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

bind-key -n C-S-Left swap-window -d -t -1
bind-key -n C-S-Right swap-window -d -t +1

bind C-b switch-client -l

bind -T copy-mode-vi 'v' send -X begin-selection
#bind -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

bind x kill-pane # Close panes without confirmation
bind R source-file ~/.config/tmux/tmux.conf \; display 'Config reloaded'

bind g popup -E -w 90% -h 90% -x C -y C -b none -d '#{pane_current_path}' "lazygit"

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Configure the catppuccin plugin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_current_text " #W "
set -g @catppuccin_window_text " #W "

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Custom status line
set -g status-left-length 100
set -g status-right-length 100
set -g window-status-separator ''
set -g status-left '#{E:@catppuccin_status_session}'
set -gF status-right '#{E:@catppuccin_status_continuum}#{E:@catppuccin_status_battery}'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-battery'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
